import Mathlib

/-!
# Kagey's Problem 137 — the tree of rationals generated by `x ↦ x + 1` and `x ↦ -1/x`

Lean 4 / Mathlib formalization of the paper `problem137.tex` (A. Pemmasani, August 2026).

Starting from `0` and repeatedly applying `f x = x + 1` and `g x = -1/x` (never applying `g`
to `0`) produces every rational number.  The *rank* `d x` of a rational `x` is the least number
of applications needed.  Problem 137 asks:

* **Q1.** Is `a n = a (n-1) + a (n-3)` for all `n ≥ 4`, where `a n = #{x : d x = n}`?
* **Q2.** Is the last map applied on a shortest path to `x` equal to `g` iff `x < 0`?
* **Q3.** Can the rank-`n` rationals be characterized?

## What is proved here

* `Kagey137.rank` is the graph-theoretic rank (length of a shortest admissible word), defined
  via the inductive predicate `Reach n x`.
* `Kagey137.P` is the parent map (`x - 1` for `x > 0`, `-1/x` for `x < 0`) and `Kagey137.D x`
  the number of steps its orbit needs to reach `0`.  `exists_iterate_P_eq_zero` is the
  termination lemma (Lemma 3.2 of the paper).
* `D1`–`D4` are the increment identities (Lemma 3.5), and `rank_eq_D` is the exact distance
  formula, Theorem 3.6 (dynamic form of Theorem B).  In particular every rational is
  reachable (`reachable`).
* `parent_unique`, `blue_iff_neg`, `red_iff_pos` and the `rank_*` lemmas give Theorem C
  (unique parent, the answer to Q2, the children rules).
* `D_hj` / `rank_hj` is the negative-continued-fraction form of the distance formula
  (Theorem 4.2), and `exists_hj` the existence half of Lemma 4.1; together they give the
  explicit description of the positive part of rank `n` (`pos_rank_iff`, answering Q3).
* The counting section proves the class recurrences of Proposition 5.3 as set identities,
  shows every rank is finite, and derives Theorem A: `a_recurrence`
  (`a (n+4) = a (n+3) + a (n+1)`), `a_three_ne` (failure at `n = 3`), `a_eq_seq`
  (`a` is A097333 shifted) and `r_eq_narayana` (the positive part is Narayana's cows, A000930).
* `rank_neg_succ`: `d (-n) = 3n - 1` (Remark 8.1).
-/

namespace Kagey137

open Function Set

/-! ### The graph, admissible words, and the rank -/

/-- `Reach n x` holds when some admissible word of length `n` in the maps `f x = x + 1` and
`g x = -1/x` sends `0` to `x`; `g` is never applied to `0`.  This is "there is a directed path
of length `n` from `0` to `x` in the graph `G`" of Definition 2.1. -/
inductive Reach : ℕ → ℚ → Prop
  | zero : Reach 0 0
  | f {n : ℕ} {x : ℚ} : Reach n x → Reach (n + 1) (x + 1)
  | g {n : ℕ} {x : ℚ} : Reach n x → x ≠ 0 → Reach (n + 1) (-1 / x)

/-! ### The parent map -/

/-- The parent map `P` of Definition 3.1, extended by `P 0 = 0`. -/
def P (x : ℚ) : ℚ := if 0 < x then x - 1 else if x < 0 then -1 / x else 0

@[simp] lemma P_zero : P 0 = 0 := by simp [P]

lemma P_pos {x : ℚ} (h : 0 < x) : P x = x - 1 := by simp [P, h]

lemma P_neg {x : ℚ} (h : x < 0) : P x = -1 / x := by simp [P, h, not_lt.mpr h.le]

lemma neg_one_div_neg {x : ℚ} (h : 0 < x) : -1 / x < 0 := by
  rw [neg_div]; exact neg_neg_of_pos (one_div_pos.mpr h)

lemma neg_one_div_pos {x : ℚ} (h : x < 0) : 0 < -1 / x := by
  rw [neg_div]; exact neg_pos.mpr (one_div_neg.mpr h)

/-- `g` is an involution (also at `0`, with Lean's convention `1/0 = 0`). -/
lemma neg_one_div_neg_one_div (x : ℚ) : -1 / (-1 / x) = x := by
  rw [div_div_eq_mul_div, neg_one_mul, div_neg, div_one, neg_neg]

lemma one_div_neg_one_div (x : ℚ) : 1 / (-1 / x) = -x := by
  rw [div_div_eq_mul_div, one_mul, div_neg, div_one]

/-- Iterating `P` from a positive rational subtracts `1` as long as the value stays positive. -/
lemma iterate_P_sub (k : ℕ) : ∀ x : ℚ, (k : ℚ) < x + 1 → P^[k] x = x - k := by
  induction k with
  | zero => intro x _; simp
  | succ k ih =>
    intro x hx
    have hk : (0 : ℚ) ≤ k := Nat.cast_nonneg k
    push_cast at hx
    have hpos : 0 < x := by linarith
    rw [iterate_succ_apply, P_pos hpos, ih (x - 1) (by linarith)]
    push_cast; ring

/-- For `-1 < z < 0` the numerator of `z` is smaller in absolute value than its denominator. -/
lemma natAbs_num_lt_den {z : ℚ} (h1 : -1 < z) (h2 : z < 0) : z.num.natAbs < z.den := by
  have hd : (0 : ℚ) < z.den := by exact_mod_cast z.den_pos
  have hnum : (z.num : ℚ) = z * z.den := (Rat.mul_den_eq_num z).symm
  have ha : -(z.den : ℚ) < z.num := by rw [hnum]; nlinarith
  have hb : (z.num : ℚ) < 0 := by rw [hnum]; exact mul_neg_of_neg_of_pos h2 hd
  have ha' : -(z.den : ℤ) < z.num := by exact_mod_cast ha
  have hb' : z.num < 0 := by exact_mod_cast hb
  omega

/-- The flip `z ↦ -1/z` strictly decreases the denominator on `(-1, 0)`
(the key step of the termination Lemma 3.2). -/
lemma den_neg_one_div_lt {z : ℚ} (h1 : -1 < z) (h2 : z < 0) : (-1 / z).den < z.den := by
  have e : -1 / z = -(z⁻¹) := by rw [neg_div, one_div]
  rw [e, Rat.den_neg_eq_den, Rat.den_inv_of_ne_zero h2.ne]
  exact natAbs_num_lt_den h1 h2

/-- **Termination (Lemma 3.2).** The `P`-orbit of every rational reaches `0`. -/
theorem exists_iterate_P_eq_zero (x : ℚ) : ∃ n, P^[n] x = 0 := by
  -- First for `x > 0` and for `-1 < x < 0`, by strong induction on the denominator.
  have key : ∀ d : ℕ, ∀ x : ℚ, x.den = d → (0 < x ∨ (-1 < x ∧ x < 0)) →
      ∃ n, P^[n] x = 0 := by
    intro d
    induction' d using Nat.strong_induction_on with d ih
    intro x hd hx
    rcases hx with hx | ⟨h1, h2⟩
    · set k := ⌈x⌉₊ with hk
      have hkx : (k : ℚ) < x + 1 := Nat.ceil_lt_add_one hx.le
      have hxk : x ≤ k := Nat.le_ceil x
      have hit : P^[k] x = x - k := iterate_P_sub k x hkx
      rcases hxk.lt_or_eq with hlt | heq
      · have hz1 : -1 < x - k := by linarith
        have hz2 : x - k < 0 := by linarith
        have hden : (-1 / (x - k)).den < d := by
          rw [← hd, ← Rat.sub_natCast_den x k]; exact den_neg_one_div_lt hz1 hz2
        obtain ⟨n, hn⟩ := ih _ hden (-1 / (x - k)) rfl (Or.inl (neg_one_div_pos hz2))
        refine ⟨n + 1 + k, ?_⟩
        rw [iterate_add_apply, hit, iterate_succ_apply, P_neg hz2, hn]
      · exact ⟨k, by rw [hit, heq, sub_self]⟩
    · have hden : (-1 / x).den < d := by rw [← hd]; exact den_neg_one_div_lt h1 h2
      obtain ⟨n, hn⟩ := ih _ hden (-1 / x) rfl (Or.inl (neg_one_div_pos h2))
      exact ⟨n + 1, by rw [iterate_succ_apply, P_neg h2, hn]⟩
  rcases lt_trichotomy x 0 with hx | rfl | hx
  · by_cases h : -1 < x
    · exact key _ x rfl (Or.inr ⟨h, hx⟩)
    · obtain ⟨n, hn⟩ := key _ (-1 / x) rfl (Or.inl (neg_one_div_pos hx))
      exact ⟨n + 1, by rw [iterate_succ_apply, P_neg hx, hn]⟩
  · exact ⟨0, rfl⟩
  · exact key _ x rfl (Or.inl hx)

/-! ### The orbit length `D` -/

/-- `D x` is the number of steps in which the `P`-orbit of `x` reaches `0` (Definition 3.3). -/
noncomputable def D (x : ℚ) : ℕ := sInf {n | P^[n] x = 0}

lemma iterate_D (x : ℚ) : P^[D x] x = 0 := Nat.sInf_mem (exists_iterate_P_eq_zero x)

lemma D_le {x : ℚ} {n : ℕ} (h : P^[n] x = 0) : D x ≤ n := Nat.sInf_le h

@[simp] lemma D_zero : D 0 = 0 := by
  have := D_le (x := 0) (n := 0) rfl
  omega

/-- The recursion `D x = D (P x) + 1` for `x ≠ 0`. -/
lemma D_succ {x : ℚ} (hx : x ≠ 0) : D x = D (P x) + 1 := by
  apply le_antisymm
  · apply D_le
    rw [iterate_succ_apply]
    exact iterate_D (P x)
  · have h := iterate_D x
    have hpos : D x ≠ 0 := by
      intro h0
      rw [h0] at h
      exact hx h
    obtain ⟨m, hm⟩ := Nat.exists_eq_succ_of_ne_zero hpos
    rw [hm, iterate_succ_apply] at h
    have := D_le h
    omega

lemma D_eq_zero_iff {x : ℚ} : D x = 0 ↔ x = 0 := by
  constructor
  · intro h
    by_contra hx
    rw [D_succ hx] at h
    omega
  · rintro rfl; exact D_zero

/-! ### The increment identities (Lemma 3.5) -/

/-- (D1) -/
lemma D1 {x : ℚ} (h : 0 < x) : D x = D (x - 1) + 1 := by rw [D_succ h.ne', P_pos h]

/-- (D2) -/
lemma D2 {x : ℚ} (h : x < 0) : D x = D (-1 / x) + 1 := by rw [D_succ h.ne, P_neg h]

/-- (D3) -/
lemma D3 {x : ℚ} (h : 0 < x) : D (-1 / x) = D x + 1 := by
  rw [D2 (neg_one_div_neg h), neg_one_div_neg_one_div]

/-- (D4): the crucial four-step computation, the shadow of `(g ∘ f)³ = id`. -/
lemma D4 {x : ℚ} (h : x < 0) : D (x - 1) = D x + 3 := by
  have h1 : x - 1 < 0 := by linarith
  have h1x : 0 < 1 - x := by linarith
  have e1 : -1 / (x - 1) = 1 / (1 - x) := by
    rw [div_eq_div_iff h1.ne h1x.ne']; ring
  have h2 : 0 < 1 / (1 - x) := one_div_pos.mpr h1x
  have e2 : 1 / (1 - x) - 1 = x / (1 - x) := by
    field_simp; ring
  have h3 : x / (1 - x) < 0 := div_neg_of_neg_of_pos h h1x
  have e3 : -1 / (x / (1 - x)) = 1 - 1 / x := by
    have hx0 : x ≠ 0 := h.ne
    field_simp; ring
  have h4 : 0 < 1 - 1 / x := by
    have := one_div_neg.mpr h
    linarith
  have e4 : 1 - 1 / x - 1 = -1 / x := by ring
  rw [D2 h1, e1, D1 h2, e2, D2 h3, e3, D1 h4, e4, D2 h]

/-- The Bellman inequality along an `f`-edge (the five-case check in the proof of
Theorem 3.6). -/
lemma D_add_one_le (x : ℚ) : D (x + 1) ≤ D x + 1 := by
  rcases lt_trichotomy (x + 1) 0 with h | h | h
  · have := D4 h
    rw [add_sub_cancel_right] at this
    omega
  · rw [h, D_zero]; omega
  · rw [D1 h, add_sub_cancel_right]

/-- The Bellman inequality along a `g`-edge. -/
lemma D_neg_one_div_le {x : ℚ} (hx : x ≠ 0) : D (-1 / x) ≤ D x + 1 := by
  rcases lt_or_gt_of_ne hx with h | h
  · rw [D2 h]; omega
  · rw [D3 h]

/-! ### The exact distance formula (Theorem 3.6) -/

/-- Upper bound: the reversed `P`-orbit is an admissible word of length `D x` ending at `x`. -/
theorem reach_of_D_eq : ∀ (n : ℕ) (x : ℚ), D x = n → Reach n x := by
  intro n
  induction n with
  | zero =>
    intro x hx
    rw [D_eq_zero_iff] at hx
    rw [hx]; exact Reach.zero
  | succ n ih =>
    intro x hx
    have hne : x ≠ 0 := by
      rintro rfl
      rw [D_zero] at hx
      omega
    rw [D_succ hne] at hx
    have hP := ih (P x) (by omega)
    rcases lt_or_gt_of_ne hne with h | h
    · rw [P_neg h] at hP
      have := Reach.g hP (div_ne_zero (by norm_num) h.ne)
      rwa [neg_one_div_neg_one_div] at this
    · rw [P_pos h] at hP
      have := Reach.f hP
      rwa [sub_add_cancel] at this

/-- Lower bound: no admissible word is shorter than the `P`-orbit. -/
theorem D_le_of_reach {n : ℕ} {x : ℚ} (h : Reach n x) : D x ≤ n := by
  induction h with
  | zero => simp
  | f _ ih => exact (D_add_one_le _).trans (by omega)
  | g _ hne ih => exact (D_neg_one_div_le hne).trans (by omega)

/-- Every rational is reachable from `0`. -/
theorem exists_reach (x : ℚ) : ∃ n, Reach n x := ⟨D x, reach_of_D_eq _ _ rfl⟩

/-- The rank `d x` of Definition 2.1: the least length of an admissible word producing `x`. -/
noncomputable def rank (x : ℚ) : ℕ := sInf {n | Reach n x}

lemma reach_rank (x : ℚ) : Reach (rank x) x := Nat.sInf_mem (exists_reach x)

lemma rank_le {n : ℕ} {x : ℚ} (h : Reach n x) : rank x ≤ n := Nat.sInf_le h

/-- **Theorem 3.6 (exact distance formula, dynamic form).** The rank of `x` is the number of
steps the parent map needs to bring `x` to `0`. -/
theorem rank_eq_D (x : ℚ) : rank x = D x :=
  le_antisymm (rank_le (reach_of_D_eq _ _ rfl)) (D_le_of_reach (reach_rank x))

/-- Every rational is produced by the construction (Theorem 3.6, first part). -/
theorem reachable (x : ℚ) : ∃ n, Reach n x := exists_reach x

/-- The rank is the length of a shortest admissible word: `Reach (rank x) x` holds, and
`Reach n x` implies `rank x ≤ n`. -/
theorem rank_spec (x : ℚ) : Reach (rank x) x ∧ ∀ n, Reach n x → rank x ≤ n :=
  ⟨reach_rank x, fun _ h => rank_le h⟩

/-! ### The in-neighbour table (Corollary 3.7) in terms of `rank` -/

@[simp] theorem rank_zero : rank 0 = 0 := by rw [rank_eq_D, D_zero]

theorem rank_eq_zero_iff {x : ℚ} : rank x = 0 ↔ x = 0 := by rw [rank_eq_D, D_eq_zero_iff]

theorem rank_of_pos {x : ℚ} (h : 0 < x) : rank x = rank (x - 1) + 1 := by
  rw [rank_eq_D, rank_eq_D]; exact D1 h

theorem rank_of_neg {x : ℚ} (h : x < 0) : rank x = rank (-1 / x) + 1 := by
  rw [rank_eq_D, rank_eq_D]; exact D2 h

theorem rank_neg_one_div_of_pos {x : ℚ} (h : 0 < x) : rank (-1 / x) = rank x + 1 := by
  rw [rank_eq_D, rank_eq_D]; exact D3 h

theorem rank_sub_one_of_neg {x : ℚ} (h : x < 0) : rank (x - 1) = rank x + 3 := by
  rw [rank_eq_D, rank_eq_D]; exact D4 h

theorem rank_add_one_of_pos {x : ℚ} (h : 0 < x) : rank (x + 1) = rank x + 1 := by
  have := rank_of_pos (by linarith : 0 < x + 1)
  rwa [add_sub_cancel_right] at this

theorem rank_add_one_of_Ioo {x : ℚ} (h1 : -1 < x) (_h2 : x < 0) :
    rank (x + 1) = rank x + 1 := by
  have := rank_of_pos (by linarith : 0 < x + 1)
  rwa [add_sub_cancel_right] at this

theorem rank_of_lt_neg_one {x : ℚ} (h : x < -1) : rank x = rank (x + 1) + 3 := by
  have := rank_sub_one_of_neg (by linarith : x + 1 < 0)
  rwa [add_sub_cancel_right] at this

theorem rank_one : rank 1 = 1 := by
  rw [rank_of_pos one_pos, sub_self, rank_zero]

theorem rank_eq_one_iff {x : ℚ} : rank x = 1 ↔ x = 1 := by
  constructor
  · intro h
    have hx : x ≠ 0 := by rintro rfl; simp at h
    rcases lt_or_gt_of_ne hx with hneg | hpos
    · rw [rank_of_neg hneg] at h
      have h' : rank (-1 / x) = 0 := by omega
      rw [rank_eq_zero_iff, div_eq_zero_iff] at h'
      rcases h' with h' | h'
      · norm_num at h'
      · exact absurd h' hx
    · rw [rank_of_pos hpos] at h
      have h' : rank (x - 1) = 0 := by omega
      rw [rank_eq_zero_iff] at h'
      linarith
  · rintro rfl; exact rank_one

theorem rank_neg_one : rank (-1) = 2 := by
  rw [rank_of_neg (by norm_num), show (-1 : ℚ) / -1 = 1 by norm_num, rank_one]

/-! ### Theorem C: tree structure and the answer to Q2 -/

/-- **Unique parent (Corollary 3.8 (a)).**  If `y → x` is an edge of `G` (`x = y + 1`, or
`x = -1/y` with `y ≠ 0`) and `y` lies one rank below `x`, then `y` is the parent `P x`.
Hence no value is ever produced twice, even within one generation. -/
theorem parent_unique {x y : ℚ} (hx : x ≠ 0) (hy : rank y + 1 = rank x)
    (hedge : y + 1 = x ∨ (y ≠ 0 ∧ -1 / y = x)) : y = P x := by
  rcases hedge with rfl | ⟨hy0, rfl⟩
  · rcases lt_trichotomy (y + 1) 0 with h | h | h
    · have := rank_sub_one_of_neg h
      rw [add_sub_cancel_right] at this
      omega
    · exact absurd h hx
    · rw [P_pos h, add_sub_cancel_right]
  · rcases lt_or_gt_of_ne hy0 with h | h
    · have := rank_of_neg h
      omega
    · rw [P_neg (neg_one_div_neg h), neg_one_div_neg_one_div]

/-- **Answer to Q2 (Corollary 3.8 (b)).**  A vertex `x ≠ 0` is entered by a `g`-edge from a
vertex one rank below (it is *blue*) if and only if `x < 0`. -/
theorem blue_iff_neg {x : ℚ} (hx : x ≠ 0) :
    (∃ y, rank y + 1 = rank x ∧ y ≠ 0 ∧ -1 / y = x) ↔ x < 0 := by
  constructor
  · rintro ⟨y, hy, hy0, rfl⟩
    rcases lt_or_gt_of_ne hy0 with h | h
    · have := rank_of_neg h
      omega
    · exact neg_one_div_neg h
  · intro h
    refine ⟨-1 / x, ?_, div_ne_zero (by norm_num) hx, neg_one_div_neg_one_div x⟩
    rw [rank_of_neg h]

/-- A vertex `x ≠ 0` is entered by an `f`-edge from a vertex one rank below (it is *red*)
if and only if `0 < x`. -/
theorem red_iff_pos {x : ℚ} (hx : x ≠ 0) :
    (∃ y, rank y + 1 = rank x ∧ y + 1 = x) ↔ 0 < x := by
  constructor
  · rintro ⟨y, hy, rfl⟩
    rcases lt_trichotomy (y + 1) 0 with h | h | h
    · have := rank_sub_one_of_neg h
      rw [add_sub_cancel_right] at this
      omega
    · exact absurd h hx
    · exact h
  · intro h
    exact ⟨x - 1, by rw [rank_of_pos h], sub_add_cancel x 1⟩

/-- **Children (Corollary 3.8 (c)).**  A positive vertex has both out-neighbours as children. -/
theorem children_of_pos {x : ℚ} (h : 0 < x) :
    rank (x + 1) = rank x + 1 ∧ rank (-1 / x) = rank x + 1 :=
  ⟨rank_add_one_of_pos h, rank_neg_one_div_of_pos h⟩

/-- A vertex in `(-1, 0)` has `x + 1` as its only child; `-1/x` is its parent. -/
theorem children_of_Ioo {x : ℚ} (h1 : -1 < x) (h2 : x < 0) :
    rank (x + 1) = rank x + 1 ∧ rank (-1 / x) + 1 = rank x :=
  ⟨rank_add_one_of_Ioo h1 h2, (rank_of_neg h2).symm⟩

/-- A vertex `x ≤ -1` is a leaf: neither out-neighbour lies one rank above it. -/
theorem leaf_of_le_neg_one {x : ℚ} (h : x ≤ -1) :
    rank (x + 1) ≠ rank x + 1 ∧ rank (-1 / x) ≠ rank x + 1 := by
  constructor
  · rcases h.lt_or_eq with h | rfl
    · have := rank_of_lt_neg_one h
      omega
    · rw [show (-1 : ℚ) + 1 = 0 by norm_num, rank_zero]
      omega
  · have := rank_of_neg (by linarith : x < 0)
    omega

/-- For `x < -1` the blocked value `x + 1` is exactly three ranks old. -/
theorem uncle_three {x : ℚ} (h : x < -1) : rank (x + 1) + 3 = rank x :=
  (rank_of_lt_neg_one h).symm

/-! ### Negative continued fractions (Section 4) -/

/-- The negative (Hirzebruch–Jung) continued fraction
`hj [c₁, …, c_k] = c₁ - 1/(c₂ - 1/(⋯ - 1/c_k))`.  Because `1/0 = 0` in Lean, the convention
`hj [] = 0` makes `hj [c] = c`. -/
def hj : List ℕ → ℚ
  | [] => 0
  | c :: cs => c - 1 / hj cs

@[simp] lemma hj_nil : hj [] = 0 := rfl

@[simp] lemma hj_cons (c : ℕ) (cs : List ℕ) : hj (c :: cs) = c - 1 / hj cs := rfl

lemma hj_singleton (c : ℕ) : hj [c] = c := by simp

/-- Tails with all digits `≥ 2` exceed `1` (Lemma 4.1). -/
lemma one_lt_hj : ∀ cs : List ℕ, cs ≠ [] → (∀ c ∈ cs, 2 ≤ c) → 1 < hj cs
  | [], h, _ => absurd rfl h
  | [c], _, h => by
    have := h c (by simp)
    simp only [hj_cons, hj_nil, div_zero, sub_zero]
    exact_mod_cast (by omega : 1 < c)
  | c :: d :: cs, _, h => by
    have ih := one_lt_hj (d :: cs) (by simp) (fun x hx => h x (by simp [hx]))
    have hc : (2 : ℚ) ≤ c := by exact_mod_cast h c (by simp)
    have : 1 / hj (d :: cs) < 1 := by
      rw [div_lt_one (by linarith)]; exact ih
    rw [hj_cons]
    linarith

lemma D_natCast (n : ℕ) : D (n : ℚ) = n := by
  induction n with
  | zero => simp
  | succ n ih => rw [Nat.cast_succ, D1 (by positivity), add_sub_cancel_right, ih]

lemma D_add_natCast {z : ℚ} (h1 : -1 < z) (_h2 : z < 0) (k : ℕ) : D (z + k) = D z + k := by
  induction k with
  | zero => simp
  | succ k ih =>
    have hk : (0 : ℚ) ≤ k := Nat.cast_nonneg k
    rw [Nat.cast_succ, ← add_assoc, D1 (by linarith), add_sub_cancel_right, ih]
    ring

/-- **Theorem 4.2 (distance formula, negative-continued-fraction form).**
If `c₁ ≥ 1` and `c₂, …, c_k ≥ 2` then `d [c₁, …, c_k]⁻ = c₁ + ⋯ + c_k + k - 1`. -/
theorem D_hj : ∀ (c : ℕ) (cs : List ℕ), 1 ≤ c → (∀ d ∈ cs, 2 ≤ d) →
    D (hj (c :: cs)) = c + cs.sum + cs.length
  | c, [], _, _ => by simp [D_natCast]
  | c, d :: cs, _, h => by
    have hy := one_lt_hj (d :: cs) (by simp) h
    have ih := D_hj d cs (by have := h d (by simp); omega) (fun x hx => h x (by simp [hx]))
    have hz1 : -1 < -1 / hj (d :: cs) := by
      rw [neg_div, neg_lt_neg_iff, div_lt_one (by linarith)]; exact hy
    have hz2 : -1 / hj (d :: cs) < 0 := neg_one_div_neg (by linarith)
    have e : hj (c :: d :: cs) = -1 / hj (d :: cs) + c := by rw [hj_cons]; ring
    rw [e, D_add_natCast hz1 hz2, D2 hz2, neg_one_div_neg_one_div, ih]
    simp only [List.sum_cons, List.length_cons]
    omega

theorem rank_hj (c : ℕ) (cs : List ℕ) (hc : 1 ≤ c) (hcs : ∀ d ∈ cs, 2 ≤ d) :
    rank (hj (c :: cs)) = c + cs.sum + cs.length := by
  rw [rank_eq_D]; exact D_hj c cs hc hcs

/-- **Existence of the expansion (Lemma 4.1).** Every positive rational is `hj (c :: cs)` with
`c = ⌈x⌉₊ ≥ 1` and all digits of `cs` at least `2`. -/
theorem exists_hj {x : ℚ} (hx : 0 < x) :
    ∃ c cs, c = ⌈x⌉₊ ∧ 1 ≤ c ∧ (∀ d ∈ cs, 2 ≤ d) ∧ hj (c :: cs) = x := by
  have key : ∀ d : ℕ, ∀ x : ℚ, x.den = d → 0 < x →
      ∃ c cs, c = ⌈x⌉₊ ∧ 1 ≤ c ∧ (∀ d ∈ cs, 2 ≤ d) ∧ hj (c :: cs) = x := by
    intro d
    induction' d using Nat.strong_induction_on with d ih
    intro x hd hx
    set k := ⌈x⌉₊ with hk
    have hxk : x ≤ k := Nat.le_ceil x
    have hkx : (k : ℚ) < x + 1 := Nat.ceil_lt_add_one hx.le
    have hk1 : 1 ≤ k := Nat.ceil_pos.mpr hx
    rcases hxk.lt_or_eq with hlt | heq
    · -- non-integer: recurse on `x' = -1/(x - k) = 1/(k - x) > 1`
      have hz1 : -1 < x - k := by linarith
      have hz2 : x - k < 0 := by linarith
      have hden : (-1 / (x - k)).den < d := by
        rw [← hd, ← Rat.sub_natCast_den x k]; exact den_neg_one_div_lt hz1 hz2
      have hx' : 1 < -1 / (x - k) := by
        rw [neg_div, ← div_neg, one_lt_div (by linarith)]; linarith
      obtain ⟨c', cs', hc', -, hcs', he⟩ := ih _ hden (-1 / (x - k)) rfl (by linarith)
      refine ⟨k, c' :: cs', rfl, hk1, ?_, ?_⟩
      · intro e he'
        rcases List.mem_cons.mp he' with rfl | he'
        · have : 1 < ⌈-1 / (x - k)⌉₊ := Nat.lt_ceil.mpr (by exact_mod_cast hx')
          omega
        · exact hcs' e he'
      · rw [hj_cons, he, one_div_neg_one_div]; ring
    · exact ⟨k, [], rfl, hk1, by simp, by rw [hj_singleton, heq]⟩
  exact key _ x rfl hx

/-- **Answer to Q3 (Corollary 4.3, positive part).** A positive rational has rank `n` iff it
is the value of a digit string `(c₁, …, c_k)` with `c₁ ≥ 1`, `c_i ≥ 2` for `i ≥ 2`, of weight
`c₁ + ⋯ + c_k + k - 1 = n`. -/
theorem pos_rank_iff {x : ℚ} (hx : 0 < x) (n : ℕ) :
    rank x = n ↔ ∃ c cs, 1 ≤ c ∧ (∀ d ∈ cs, 2 ≤ d) ∧ hj (c :: cs) = x ∧
      c + cs.sum + cs.length = n := by
  constructor
  · intro h
    obtain ⟨c, cs, -, hc, hcs, he⟩ := exists_hj hx
    exact ⟨c, cs, hc, hcs, he, by rw [← h, ← he, rank_hj c cs hc hcs]⟩
  · rintro ⟨c, cs, hc, hcs, rfl, rfl⟩
    exact rank_hj c cs hc hcs

/-- The negative part of rank `n + 1` is `-1/y` over the positives `y` of rank `n`
(Corollary 4.3, second line). -/
theorem neg_rank_iff {x : ℚ} (hx : x < 0) (n : ℕ) :
    rank x = n + 1 ↔ rank (-1 / x) = n := by
  rw [rank_of_neg hx]; omega

/-! ### Counting: Theorem A -/

/-- The rank-`n` sphere `X n = {x | d x = n}`. -/
def X (n : ℕ) : Set ℚ := {x | rank x = n}

/-- The positive rationals of rank `n`. -/
def Pos (n : ℕ) : Set ℚ := {x | rank x = n ∧ 0 < x}

/-- The negative rationals of rank `n`. -/
def Neg (n : ℕ) : Set ℚ := {x | rank x = n ∧ x < 0}

/-- Class `(1, ∞)` of Proposition 5.3. -/
def A (n : ℕ) : Set ℚ := {x | rank x = n ∧ 1 < x}

/-- Class `(0, 1]` of Proposition 5.3. -/
def B (n : ℕ) : Set ℚ := {x | rank x = n ∧ 0 < x ∧ x ≤ 1}

/-- Class `(-1, 0)` of Proposition 5.3. -/
def C (n : ℕ) : Set ℚ := {x | rank x = n ∧ -1 < x ∧ x < 0}

/-- `a n = |X n|`, the number of rationals of rank `n`. -/
noncomputable def a (n : ℕ) : ℕ := (X n).ncard

/-- `r n`, the number of positive rationals of rank `n`. -/
noncomputable def r (n : ℕ) : ℕ := (Pos n).ncard

lemma X_zero : X 0 = {0} := by
  ext x; simp [X, rank_eq_zero_iff]

lemma X_succ (n : ℕ) : X (n + 1) = Pos (n + 1) ∪ Neg (n + 1) := by
  ext x
  simp only [X, Pos, Neg, mem_ofPred_eq, mem_union]
  constructor
  · intro h
    have hx : x ≠ 0 := by rintro rfl; rw [rank_zero] at h; omega
    rcases lt_or_gt_of_ne hx with h' | h'
    · exact Or.inr ⟨h, h'⟩
    · exact Or.inl ⟨h, h'⟩
  · rintro (⟨h, _⟩ | ⟨h, _⟩) <;> exact h

/-- The negatives of rank `n + 1` are the images `-1/y` of the positives of rank `n`. -/
lemma Neg_succ (n : ℕ) : Neg (n + 1) = (fun y => -1 / y) '' Pos n := by
  ext x
  simp only [Neg, Pos, mem_ofPred_eq, mem_image]
  constructor
  · rintro ⟨h, hx⟩
    refine ⟨-1 / x, ⟨?_, neg_one_div_pos hx⟩, neg_one_div_neg_one_div x⟩
    rw [rank_of_neg hx] at h; omega
  · rintro ⟨y, ⟨hy, hy0⟩, rfl⟩
    exact ⟨by rw [rank_neg_one_div_of_pos hy0, hy], neg_one_div_neg hy0⟩

lemma Pos_eq (n : ℕ) : Pos n = A n ∪ B n := by
  ext x
  simp only [Pos, A, B, mem_ofPred_eq, mem_union]
  constructor
  · rintro ⟨h, hx⟩
    by_cases h1 : 1 < x
    · exact Or.inl ⟨h, h1⟩
    · exact Or.inr ⟨h, hx, not_lt.mp h1⟩
  · rintro (⟨h, h1⟩ | ⟨h, h1, _⟩)
    · exact ⟨h, by linarith⟩
    · exact ⟨h, h1⟩

/-- Rule `α_{n+1} = α_n + β_n`: the `f`-children of the positives fill `(1, ∞)`. -/
lemma A_succ (n : ℕ) : A (n + 1) = (· + 1) '' Pos n := by
  ext x
  simp only [A, Pos, mem_ofPred_eq, mem_image]
  constructor
  · rintro ⟨h, hx⟩
    refine ⟨x - 1, ⟨?_, by linarith⟩, sub_add_cancel x 1⟩
    rw [rank_of_pos (by linarith)] at h; omega
  · rintro ⟨y, ⟨hy, hy0⟩, rfl⟩
    exact ⟨by rw [rank_add_one_of_pos hy0, hy], by linarith⟩

/-- Rule `β_{n+1} = γ_n` (for `n ≥ 1`): the `f`-children of `(-1, 0)` fill `(0, 1]`. -/
lemma B_succ (n : ℕ) (hn : 1 ≤ n) : B (n + 1) = (· + 1) '' C n := by
  ext x
  simp only [B, C, mem_ofPred_eq, mem_image]
  constructor
  · rintro ⟨h, hx0, hx1⟩
    refine ⟨x - 1, ⟨?_, by linarith, ?_⟩, sub_add_cancel x 1⟩
    · rw [rank_of_pos hx0] at h; omega
    · rcases hx1.lt_or_eq with h1 | rfl
      · linarith
      · rw [rank_one] at h; omega
  · rintro ⟨y, ⟨hy, hy1, hy2⟩, rfl⟩
    exact ⟨by rw [rank_add_one_of_Ioo hy1 hy2, hy], by linarith, by linarith⟩

/-- Rule `γ_{n+1} = α_n`: the `g`-children of `(1, ∞)` fill `(-1, 0)`. -/
lemma C_succ (n : ℕ) : C (n + 1) = (fun y => -1 / y) '' A n := by
  ext x
  simp only [C, A, mem_ofPred_eq, mem_image]
  constructor
  · rintro ⟨h, hx1, hx2⟩
    refine ⟨-1 / x, ⟨?_, ?_⟩, neg_one_div_neg_one_div x⟩
    · rw [rank_of_neg hx2] at h; omega
    · rw [neg_div, ← div_neg, one_lt_div (by linarith)]; linarith
  · rintro ⟨y, ⟨hy, hy1⟩, rfl⟩
    refine ⟨by rw [rank_neg_one_div_of_pos (by linarith), hy], ?_,
      neg_one_div_neg (by linarith)⟩
    rw [neg_div, neg_lt_neg_iff, div_lt_one (by linarith)]; exact hy1

/-- Every rank is a finite set. -/
lemma X_finite : ∀ n, (X n).Finite := by
  intro n
  induction n with
  | zero => rw [X_zero]; exact finite_singleton 0
  | succ n ih =>
    rw [X_succ]
    refine Finite.union ((ih.image (· + 1)).subset ?_) ((ih.image (fun y => -1 / y)).subset ?_)
    · rintro x ⟨h, hx⟩
      refine ⟨x - 1, ?_, sub_add_cancel x 1⟩
      show rank (x - 1) = n
      rw [rank_of_pos hx] at h; omega
    · rintro x ⟨h, hx⟩
      refine ⟨-1 / x, ?_, neg_one_div_neg_one_div x⟩
      show rank (-1 / x) = n
      rw [rank_of_neg hx] at h; omega

lemma Pos_finite (n : ℕ) : (Pos n).Finite := (X_finite n).subset (fun _ hx => hx.1)
lemma Neg_finite (n : ℕ) : (Neg n).Finite := (X_finite n).subset (fun _ hx => hx.1)
lemma A_finite (n : ℕ) : (A n).Finite := (X_finite n).subset (fun _ hx => hx.1)
lemma B_finite (n : ℕ) : (B n).Finite := (X_finite n).subset (fun _ hx => hx.1)
lemma C_finite (n : ℕ) : (C n).Finite := (X_finite n).subset (fun _ hx => hx.1)

lemma injective_neg_one_div : Function.Injective (fun y : ℚ => -1 / y) := by
  intro y y' h
  have := congrArg (fun t => -1 / t) h
  simpa only [neg_one_div_neg_one_div] using this

lemma disjoint_Pos_Neg (n : ℕ) : Disjoint (Pos n) (Neg n) := by
  rw [Set.disjoint_left]
  rintro x ⟨_, hx⟩ ⟨_, hx'⟩
  linarith

lemma disjoint_A_B (n : ℕ) : Disjoint (A n) (B n) := by
  rw [Set.disjoint_left]
  rintro x ⟨_, hx⟩ ⟨_, _, hx'⟩
  linarith

lemma a_zero : a 0 = 1 := by rw [a, X_zero, ncard_singleton]

/-- `a (n+1) = r (n+1) + r n`: the negatives of rank `n + 1` biject with the positives of
rank `n`. -/
lemma a_succ (n : ℕ) : a (n + 1) = r (n + 1) + r n := by
  rw [a, X_succ, ncard_union_eq (disjoint_Pos_Neg _) (Pos_finite _) (Neg_finite _), Neg_succ,
    ncard_image_of_injective _ injective_neg_one_div]
  rfl

lemma r_eq (n : ℕ) : r n = (A n).ncard + (B n).ncard := by
  rw [r, Pos_eq, ncard_union_eq (disjoint_A_B _) (A_finite _) (B_finite _)]

lemma ncard_A_succ (n : ℕ) : (A (n + 1)).ncard = r n := by
  rw [A_succ, ncard_image_of_injective _ (add_left_injective 1)]; rfl

lemma ncard_B_succ (n : ℕ) (hn : 1 ≤ n) : (B (n + 1)).ncard = (C n).ncard := by
  rw [B_succ n hn, ncard_image_of_injective _ (add_left_injective 1)]

lemma ncard_C_succ (n : ℕ) : (C (n + 1)).ncard = (A n).ncard := by
  rw [C_succ, ncard_image_of_injective _ injective_neg_one_div]

lemma Pos_zero : Pos 0 = ∅ := by
  ext x
  simp only [Pos, mem_ofPred_eq, mem_empty_iff_false, iff_false, not_and, rank_eq_zero_iff]
  rintro rfl; exact lt_irrefl 0

lemma A_zero : A 0 = ∅ := by
  ext x
  simp only [A, mem_ofPred_eq, mem_empty_iff_false, iff_false, not_and, rank_eq_zero_iff]
  rintro rfl; norm_num

lemma Pos_one : Pos 1 = {1} := by
  ext x
  simp only [Pos, mem_ofPred_eq, mem_singleton_iff, rank_eq_one_iff]
  constructor
  · rintro ⟨h, _⟩; exact h
  · rintro rfl; exact ⟨rfl, one_pos⟩

lemma r_zero : r 0 = 0 := by rw [r, Pos_zero, ncard_empty]

lemma r_one : r 1 = 1 := by rw [r, Pos_one, ncard_singleton]

lemma r_two : r 2 = 1 := by
  have h1 : (A 2).ncard = r 1 := ncard_A_succ 1
  have h2 : (B 2).ncard = (C 1).ncard := ncard_B_succ 1 le_rfl
  have h3 : (C 1).ncard = (A 0).ncard := ncard_C_succ 0
  rw [r_eq, h1, h2, h3, A_zero, ncard_empty, r_one]

/-- The positive counts satisfy `r (n+3) = r (n+2) + r n` (Narayana's cows). -/
lemma r_add_three (n : ℕ) : r (n + 3) = r (n + 2) + r n := by
  have h1 : r (n + 3) = (A (n + 3)).ncard + (B (n + 3)).ncard := r_eq _
  have h2 : (A (n + 3)).ncard = r (n + 2) := ncard_A_succ (n + 2)
  have h3 : (B (n + 3)).ncard = (C (n + 2)).ncard := ncard_B_succ (n + 2) (by omega)
  have h4 : (C (n + 2)).ncard = (A (n + 1)).ncard := ncard_C_succ (n + 1)
  have h5 : (A (n + 1)).ncard = r n := ncard_A_succ n
  omega

lemma a_one : a 1 = 1 := by rw [a_succ, r_one, r_zero]

lemma a_two : a 2 = 2 := by
  have h : a 2 = r 2 + r 1 := a_succ 1
  rw [h, r_two, r_one]

lemma a_three : a 3 = 2 := by
  have h1 : a 3 = r 3 + r 2 := a_succ 2
  have h2 : r 3 = r 2 + r 0 := r_add_three 0
  rw [h1, h2, r_two, r_zero]

/-- **Theorem A / answer to Q1.** `a (n + 4) = a (n + 3) + a (n + 1)` for every `n`, i.e.
`a n = a (n - 1) + a (n - 3)` for all `n ≥ 4`. -/
theorem a_recurrence (n : ℕ) : a (n + 4) = a (n + 3) + a (n + 1) := by
  have h1 : a (n + 4) = r (n + 4) + r (n + 3) := a_succ (n + 3)
  have h2 : a (n + 3) = r (n + 3) + r (n + 2) := a_succ (n + 2)
  have h3 : a (n + 1) = r (n + 1) + r n := a_succ n
  have h4 : r (n + 4) = r (n + 3) + r (n + 1) := r_add_three (n + 1)
  have h5 : r (n + 3) = r (n + 2) + r n := r_add_three n
  omega

theorem a_recurrence' {n : ℕ} (hn : 4 ≤ n) : a n = a (n - 1) + a (n - 3) := by
  obtain ⟨k, rfl⟩ : ∃ k, n = k + 4 := ⟨n - 4, by omega⟩
  rw [show k + 4 - 1 = k + 3 by omega, show k + 4 - 3 = k + 1 by omega]
  exact a_recurrence k

/-- The recurrence fails at `n = 3`: `a 3 = 2` while `a 2 + a 0 = 3`, so `n ≥ 4` is sharp. -/
theorem a_three_ne : a 3 ≠ a 2 + a 0 := by
  rw [a_three, a_two, a_zero]; decide

/-- The sequence `1, 1, 2, 2, 3, 5, 7, 10, 15, …` with generating function
`(1 + t² - t³)/(1 - t - t³)`; `seq n = A097333 (n - 1)` for `n ≥ 1`. -/
def seq : ℕ → ℕ
  | 0 => 1
  | 1 => 1
  | 2 => 2
  | 3 => 2
  | n + 4 => seq (n + 3) + seq (n + 1)

/-- `a n` is given by the closed recurrence, so `a n = A097333 (n - 1)` for `n ≥ 1`. -/
theorem a_eq_seq : ∀ n, a n = seq n := by
  intro n
  induction' n using Nat.strong_induction_on with n ih
  match n with
  | 0 => exact a_zero
  | 1 => exact a_one
  | 2 => exact a_two
  | 3 => exact a_three
  | n + 4 =>
    have i1 : a (n + 3) = seq (n + 3) := ih (n + 3) (by omega)
    have i2 : a (n + 1) = seq (n + 1) := ih (n + 1) (by omega)
    rw [a_recurrence, seq, i1, i2]

/-- Narayana's cows sequence A000930: `1, 1, 1, 2, 3, 4, 6, 9, 13, …`. -/
def narayana : ℕ → ℕ
  | 0 => 1
  | 1 => 1
  | 2 => 1
  | n + 3 => narayana (n + 2) + narayana n

/-- The number of positive rationals of rank `n + 1` is `A000930 n`. -/
theorem r_eq_narayana : ∀ n, r (n + 1) = narayana n := by
  intro n
  induction' n using Nat.strong_induction_on with n ih
  match n with
  | 0 => exact r_one
  | 1 => exact r_two
  | 2 =>
    have h : r 3 = r 2 + r 0 := r_add_three 0
    rw [h, r_two, r_zero]; rfl
  | n + 3 =>
    have h : r (n + 4) = r (n + 3) + r (n + 1) := r_add_three (n + 1)
    have i1 : r (n + 3) = narayana (n + 2) := ih (n + 2) (by omega)
    have i2 : r (n + 1) = narayana n := ih n (by omega)
    show r (n + 4) = narayana (n + 3)
    rw [h, narayana, i1, i2]

/-- The first values `a 0, …, a 5 = 1, 1, 2, 2, 3, 5`. -/
theorem a_values : a 0 = 1 ∧ a 1 = 1 ∧ a 2 = 2 ∧ a 3 = 2 ∧ a 4 = 3 ∧ a 5 = 5 := by
  simp only [a_eq_seq]; decide

/-! ### Remark 8.1: the negative integers appear at ranks `2, 5, 8, …` -/

lemma D_one_div_succ (n : ℕ) : D (1 / ((n : ℚ) + 1)) = 3 * n + 1 := by
  induction n with
  | zero =>
    have := D_natCast 1
    simpa using this
  | succ n ih =>
    have hn : (0 : ℚ) ≤ n := Nat.cast_nonneg n
    have h1 : (n : ℚ) + 1 ≠ 0 := by positivity
    have h2 : (n : ℚ) + 1 + 1 ≠ 0 := by positivity
    have hy0 : 0 < 1 / ((n : ℚ) + 1 + 1) := by positivity
    have hy1 : 1 / ((n : ℚ) + 1 + 1) < 1 := by
      rw [div_lt_one (by positivity)]; linarith
    have hz : 1 / ((n : ℚ) + 1 + 1) - 1 < 0 := by linarith
    have e0 : 1 / ((n : ℚ) + 1 + 1) - 1 = -((n : ℚ) + 1) / ((n : ℚ) + 1 + 1) := by
      field_simp; ring
    have e1 : -1 / (1 / ((n : ℚ) + 1 + 1) - 1) = 1 / ((n : ℚ) + 1) + 1 := by
      rw [e0, div_div_eq_mul_div, neg_one_mul, div_neg, neg_div, neg_neg]
      field_simp; ring
    rw [Nat.cast_succ, D1 hy0, D2 hz, e1, D1 (by positivity), add_sub_cancel_right, ih]
    ring

/-- `d (1/(n+1)) = 3n + 1`, i.e. `d (1/n) = 3n - 2` for `n ≥ 1`. -/
theorem rank_one_div_succ (n : ℕ) : rank (1 / ((n : ℚ) + 1)) = 3 * n + 1 := by
  rw [rank_eq_D]; exact D_one_div_succ n

/-- `d (-(n+1)) = 3n + 2`, i.e. `d (-n) = 3n - 1` for `n ≥ 1` (Remark 8.1). -/
theorem rank_neg_succ (n : ℕ) : rank (-((n : ℚ) + 1)) = 3 * n + 2 := by
  have hn : (0 : ℚ) ≤ n := Nat.cast_nonneg n
  have h : -((n : ℚ) + 1) < 0 := by linarith
  rw [rank_of_neg h, show -1 / -((n : ℚ) + 1) = 1 / ((n : ℚ) + 1) by
    rw [div_neg, neg_div, neg_neg], rank_one_div_succ]

end Kagey137
